# Generated by Django 4.1.7 on 2023-04-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_coder', '0004_entregables'),
    ]

    operations = [
        migrations.CreateModel(
            name='After',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_del_after', models.CharField(max_length=30)),
                ('tema_a_tocar', models.CharField(max_length=200)),
                ('hora_de_inicio', models.TimeField()),
                ('zoom', models.URLField()),
            ],
        ),
    ]
